Makefile, delivery.yaml
Move image to opensource docker registry
=> Move image to opensource docker registry

main.go, operator/autoscaler.go, operator/autoscaler_test.go, operator/elasticsearch.go, operator/elasticsearch_test.go, operator/es_client.go, operator/metrics_collector.go, operator/operator.go, operator/operator_test.go
This fixes formatting flaws which was reported by Go Report Card
- Formatting
=> Formatting go files

cmd/e2e/autoscale_test.go, cmd/e2e/basic_test.go, cmd/e2e/test_environment.go
Formatting e2e files
* e2e go files were not correctly formatted
=> Formatting e2e go files

README.md
Reverts change introduced by
https://github.com/zalando-incubator/es-operator/pull/6/commits/03710cf458974d9b8f99112c7c1964f422346be0
Signed-off-by: Oliver Trosien <oliver.trosien@zalando.de>
=> Undo README sales-pitch removal

operator/autoscaler.go, operator/autoscaler_test.go, operator/elasticsearch.go
> Issue : #7  Structured logging for autoscaler
Provides structured logging for autoscaler. 
- Refactor/improvements: Passes context to AutoScaler struct
- Improvement: Creates a logger from context 
- New feature: Warn when reaching scaling max limit
=>  #7  Structured logging for autoscaler

docs/deployment.yaml, e2e.sh
Use correct opensource image in example!
Fix: #30
=> Use correct image in example

cmd/e2e/upgrade_test.go, operator/elasticsearch.go, operator/operator.go, operator/operator_test.go, pkg/apis/zalando.org/v1/types.go
Updates the EDS status with current replicas count from StatefulSet.
Fix #26
Fix #18
=> Update EDS status when needed

operator/es_client_test.go
Improving the test coverage for the Elasticsearch client.
=> Add more tests to es_client

MAINTAINERS.md
Just removes the duplicate MAINTAINERS file (MAINTAINERS.md)
=> Remove duplicate MAINTAINERS file

e2e.sh
Filename was changed at some point. Fix the script.
=> Fix filename in e2e.sh script

operator/elasticsearch.go
Follow up to #45 to add even more context to errors.
=> Add even more context to errors around ensure operations

operator/es_client.go
Introduces a mutex to avoid race of exclude ip setting, also periodically check if the IP exclusion is still set on the cluster.
Fixes #55
=>  #55 Race condition for exclude._ip setting

.zappr.yaml
=> Use compliant zappr config

operator/operator.go
This solves the easy part of #54 namely always preferring scale-up over draining pods because of EDS upgrade or Kubernetes cluster upgrade.
I will address the handling of scale-down in a separate PR, but scale-up is the most important change especially during Kubernetes cluster upgrades.
=> Prefer scale-up over draining pods

operator/es_client.go, operator/es_client_test.go
=>  #51 Stale value in 'current-scaling-operation' causing ES Operator to fail

README.md
add official es operator into readme
=> add official es operator into readme

.golangci.yml, .travis.yml, Makefile, cmd/e2e/autoscale_test.go, cmd/e2e/basic_test.go, cmd/e2e/upgrade_test.go, manifests/rbac.yaml, operator/es_client_test.go
* Bump the version of golangci-lint
* Cleanup configuration file of golanci
> Issue : #1234 (only if appropriate)
A few sentences describing the overall goals of the pull request's
commits.
_What types of changes does your code introduce? Keep the ones that apply:_
- New feature (non-breaking change which adds functionality)
- Configuration change
- Refactor/improvements
- Documentation / non-code
_List of tasks you will do to complete the PR_
_List of tasks the reviewer must do to review the PR_
These should highlight any db migrations, feature toggles, etc.
=> Updating golangci-lint

docs/cluster-roles.yaml
Add create permissions for EMS
=> Add create permissions for EMS

.travis.yml
Only updating golangci version
=> Updating golangci

operator/autoscaler.go
Minor code cleanup on the shard-to-node ratio calculation
=> Extract shard-to-node ratio into a method

.github/workflows/ci.yaml
Update and verify that the build still works.
=> Update GH action build

docs/RELEASING.md
=> Write release documentation

docs/EMERGENCY.md
Signed-off-by: Oliver Trosien <oliver.trosien@zalando.de>
Document emergency operation, if ES-Operator is not scaling the cluster.
- Documentation / non-code
closes #251
=> Document emergency operations

operator/autoscaler.go, operator/autoscaler_test.go
This fixes the situation when updating an EDS with a lower maxIndexReplicas setting, to ensure to meet this boundary. 
If we don't update the indexReplicas down to the maxIndexReplicas setting, we will get stuck in scaling down, as we're too rapidly decreasing nodes, and only one-by-one decreasing index replicas.
_List of tasks the reviewer must do to review the PR_
=> Ensure maxIndexReplicas boundaries

operator/es_client.go
> Issue : #404
This commit integrates context cancellation checks into the retry mechanism 
of the waitForEmptyEsNode function. By incorporating this check, the function 
can now immediately respond to context cancellations and stop retry attempts.
The context check is implemented directly in the retry condition, which allows
for an immediate halt if the context is canceled, without proceeding to unnecessary
retry attempts that would fail due to the context being expired or canceled.
- Documentation / non-code
_List of tasks the reviewer must do to review the PR_
=> Implement context cancellation checking in retry mechanism for node drain
