go.mod
go.sum

Suppresses logs like:
```
ERROR: logging before flag.Parse: E0326 19:09:34.221696       1 round_trippers.go:169] CancelRequest not implemented by *rest.tokenSourceTransport
E0326 19:09:34.221866       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
```
Which comes from the timeout set on the client-go client. The logs
doesn't matter so we can simply suppress them.
As I needed to suppress similar logs in other projects I created
https://github.com/mikkeloscar/knolog which is a simple stub
implementation of https://github.com/kubernetes/klog

Suppress klog logs with a stub implementation

---

.travis.yaml
README.md

Adding badges to README.md similar to other projects we have, see https://github.com/zalando-incubator/kube-metrics-adapter.
* go report card
* release tags
* go doc reference
* test coverage through coverall
Current preview:
TravisCI and Coveralls should be activated after merging this PR.

Badges for README.md

---

.travis.yaml

roveralls should ignore e2e tests.
We already test those.

Ignore e2e test

---

delivery.yaml

We will shift from publishing docker images tagged with CDP_BUILD_VERSION to using git SHA, and git tags.
Signed-off-by: Oliver Trosien <oliver.trosien@zalando.de>

Prepare first release

---

.golangci.yml
.travis.yml
Makefile
cmd/e2e/autoscale_test.go
cmd/e2e/basic_test.go
cmd/e2e/test_environment.go
cmd/e2e/test_utils.go
operator/autoscaler.go
operator/elasticsearch.go
operator/es_client.go
operator/es_client_test.go
pkg/apis/zalando.org/v1/types.go

Golangci-lint is a linter aggregator which enables a lot of good linters like errcheck, govet and golint.
- Travis will run golangci-lint after  running tests
- More visibility for PR's

Introduce golangci-lint

---

operator/elasticsearch.go

This manually sets the correct `TypeMeta` information after updating `r.eds` when calling `UpdateStatus`. This is done because the `TypeMeta` is missing from the returned updated resource.
Should fix #43

Add TypeMeta information after updating status

---

operator/elasticsearch.go

In case of error the `eds` struct field would be overwritten with an
'empty' value and used in the next iteration of the operation loop which
would result in the errors:
```
Failed to operate resource: failed to ensure resources: resource name may not be empty
```
Instead only update the `eds` struct field when the `UpdateStatus` call
is successful.
Fix #43

Don't overwrite struct field on error

---

operator/autoscaler.go
operator/autoscaler_test.go
operator/elasticsearch.go

Only log that es-operator is scaling, if there is an actual change in replicas
es-operator keeps logging "Updating desired scaling for EDS .... New desired replicas: 20. Decreasing node replicas to 20.", although the current replicas are already 20 (=minReplicas)
> Fixes Issue #40
Ensure actual scalingDirection is properly differentiated from scalingHint. If there is no change in node count, the scalingDirection should always be NONE.

Avoid irritating scaling message

---

operator/operator.go
operator/operator_test.go

This is an optimization to prioritize pods on nodes which are marked
unschedulable higher than pods on schedulable nodes. Unschedulable nodes
indicate that the node is being drained, so it makes sense to move those
pods as soon as possible.

Prioritize pods on unschedulable nodes

---

cmd/e2e/autoscale_test.go
cmd/e2e/basic_test.go
operator/autoscaler.go
operator/autoscaler_test.go

Snap to non-fractioned scaling boundaries

---

operator/autoscaler.go
operator/autoscaler_test.go

 #66 ES Operator doesn't scale-down to its boundary

---

.travis.yml
delivery.yaml
deploy/e2e/apply/account_cdp.yaml
deploy/e2e/apply/rbac.yaml
docs/elasticsearch-cluster.yaml
docs/es-operator.yaml
go.mod
manifests/account_cdp.yaml
manifests/es-operator.yaml
manifests/rbac.yaml

Integrate RBAC role for operator to get rid of magic `cdp` serviceAccount.

Use RBAC role for operator

---

docs/cluster-roles.yaml
manifests/rbac.yaml

`elasticsearchmetricsets` doesn't have a `status` defined, so we should not need access to it via RBAC.

Drop elasticsearchmetricsets/status permissions

---

operator/operator.go

Issue : #121 
The goal off this PR is to ensure statefulset is ready before scale up. I am testing on a cluster right now it seems to correctly fix the reported issues. However I am not sure it is the best way.

wait for stable statefulset before scale replica

---

cmd/e2e/test_utils.go
deploy/e2e/apply/es6-master.yaml
deploy/e2e/apply/es7-master.yaml
deploy/e2e/apply/operator_service_account.yaml

We no longer have the *magic* `operator` service account in the cluster used for e2e. Drop the privileged part which is not needed in our clusters anyway.
Fixes e2e which are otherwise broken!

Run e2e with unprivileged pods

---

docs/elasticsearchdataset-vct.yaml

Change: Added init container to raise max_map_count.
Closes #108

VCT example fails due to not setting max_map_count

---

manifests/rbac.yaml

Add `-e2e` suffix to the clusterrole/binding used in the e2e tests to avoid overriding what may be already deployed in the cluster.

Avoid overriding existing clusterrole/binding

---

Dockerfile
Dockerfile.e2e

Uses the new alpine Docker base image to become compliant with the company's docker build policy.

Use compliant Docker image

---

operator/autoscaler.go
operator/autoscaler_test.go

> Issue : #141 
With this PR I try to fix a bug with setting minIndexReplicas on config change and update the logic for a ShardToNodeRatio param. 
Fix a function calculateNodesWithSameShardToNodeRatio, before if we have shards < nodes, the function conducts division to the number what is <1 (0 < n < 1), as a result function increases replicas.  
About an evaluation of number of nodes on checking MinShardsPerNode: looks like it makes sense to do it only in case of the new number of shards is more than MinShardsPerNode. 
Fix bug #141
Minor changes for ShardToNodeRatio param logic
_List of tasks the reviewer must do to review the PR_
These should highlight any db migrations, feature toggles, etc.

feat: Update logic for ShardToNodeRatio and MinIndexReplicas

---

Dockerfile.e2e

Upgrade the Dockerfile used in the e2e-tests to use alpine-3.13

Consistently use alpine-3.13

---

Makefile
docs/zalando.org_elasticsearchdatasets_v1beta1.yaml
docs/zalando.org_elasticsearchmetricsets_v1beta1.yaml

This introduces CRD manifests generated for the `v1beta1` api version, which allows smoother upgrade from an old v1beta1 definition without a schema defined.
The upgrade path would be this:
1. Current v1beta1 CRD without schema defined (prior to this: https://github.com/zalando-incubator/es-operator/pull/142)
2. Apply the v1beta1 CRD with schema (added in this PR) `docs/zalando.org_elasticsearchdatasets_v1beta1.yaml`
3. Apply the v1 CRD with schema: `docs/zalando.org_elasticsearchdatasets.yaml`

Add v1beta1 CRDs for smoother upgrade

---

docs/zalando.org_elasticsearchdatasets.yaml
docs/zalando.org_elasticsearchdatasets_v1beta1.yaml
go.mod
go.sum
operator/elasticsearch.go
operator/es_client.go
operator/es_client_test.go
pkg/apis/zalando.org/v1/types.go

Exclude ES-Operator from managing system indices. This can be controlled per EDS. To avoid this being a breaking change, the default setting is opt-in. 
> Issue : #161 
Added an optional setting to the EDS (spec.excludeSystemIndices). If set to true, the ES-Operator will filter out indices starting with "." (indication of an internal Elasticsearch index) when calculating shard-per-node ratio and scaling index replica counts.
It will still check all shards even ones for system indices when draining to make sure we don't terminte a node with data on it.
- New feature (non-breaking change which adds functionality)
- Configuration change
Open question: we introducing a double-negation property, which I'm not a big fan of. What do others think of that?
_List of tasks the reviewer must do to …

ES-Operator doesn't separate system indices and ordinary users indices

---

operator/elasticsearch.go

Signed-off-by: Oliver <oliver.trosien@zalando.de>
> Issue : #201 
Migrates the code from v1beta1 PodDisruptionBudget to v1.
- Refactor/improvements
Do we need to write any kind of migration for the existing v1beta1 resources?

Upgrades to v1 PodDisruptionBudget

---

operator/operator.go

This reduces the noise in the logs.
The operator logs every minute `StatefulSet x/y has z/z ready replicas`, even if the statefulset is stable already.
- Refactor/improvements

Only log StatefulSet replicas if the STS is not stable yet

---

README.md

Signed-off-by: Oliver Trosien <oliver.trosien@zalando.de>
Introduced in https://github.com/zalando-incubator/es-operator/pull/177 but not documented in the README.
Exclude ES-Operator from managing system indices. This can be controlled per EDS. To avoid this being a breaking change, the default setting is opt-in.
Added an optional setting to the EDS (spec.excludeSystemIndices). If set to true, the ES-Operator will filter out indices starting with "." (indication of an internal Elasticsearch index) when calculating shard-per-node ratio and scaling index replica counts.
It will still check all shards, even ones for system indices when draining to make sure we don't terminte a node with data on it.
_What types of changes does your code introduce? Keep the ones that apply:_
- Documentation / …

Document spec.excludeSystemIndices

---

operator/es_client.go
operator/es_client_test.go

The empty string transient exclude ips list must be overwritten to a
null so that the setting is completely removed and the persistent setting
can take effect.
Signed-off-by: Girish Chandrashekar <girish.chandrashekar@zalando.de>
The empty string value exclude ips settings is a valid value and needs to be set to null in
the transient key space to avoid overriding the setting in the persistent key space.
- Remove the logic that was skipping the overwrite to null on the transient exclude ip setting when the value was an empty string.
- One additional if statement to set the persistent exclude ip setting only if there is valid non empty transient value available. Without this the es-operator would always set the persistent exclude ips to the merged values or an empty string.
- Clean up some …

[bugfix] Ensure that empty transient string values are converted to null

---

README.md
docs/zalando.org_elasticsearchdatasets.yaml
docs/zalando.org_elasticsearchdatasets_v1beta1.yaml
operator/elasticsearch.go
operator/es_client_test.go
operator/metrics_collector.go
pkg/apis/zalando.org/v1/types.go

This is a simple proposal for how we could allow skipping of pod draining when during rolling update or scaledown of an `ElasticsearchDataSet`. It adds a field `spec.skipDraining` which when set to `true` will instruct the operator not to attempt to drain a pod before it is terminated. The field defaults to `false`.
We could also think about enabling this by default in case there are any `VolumeClaimTemplates` which is usually where you would want to not drain the pod but just terminate it and let the replacement pod remount the data from the PVC.
Fix #70

Allow skipping draining of pods during update/scaledown

---

operator/elasticsearch.go
operator/operator.go
operator/operator_test.go
pkg/client/clientset/versioned/fake/register.go
pkg/client/clientset/versioned/scheme/register.go

The ES Operator could decide to scale down, but while scaling down the thresholds for scale up are being exceeded, e.g. if we're reaching a point where we should stop scaling down.
Issue : #57 
Introduces StatefulResourceGetter interface to allow refreshing of an EDS during scaling, which happens in case the autoscaler indicated a scale-up.
- New feature (non-breaking change which adds functionality)

Abortable scale-down

---

Dockerfile
Dockerfile.e2e

Make es-operator compliant again by migrating to the alpine-3 base image.

Docker: use "alpine-3" as base image

---

.golangci.yml

The `golint` linter has been deprecated since v1.41.0 (June 15, 2021). Recently, on April 27, 2024, `golangci-lint` replaced the deprecation warning with an error for deprecated linters, including `golint` ([reference](https://github.com/golangci/golangci-lint/pull/4681#issue-2267058103)). As a result, our CI pipeline began to fail due to the usage of `golint`.
- **Removed `golint`**: `golint` has been removed from our `golangci-lint` configuration due to its deprecation and the subsequent error enforcement in `golangci-lint`.
- **Added `revive`**: Integrated `revive` as a replacement linter to continue maintaining code quality standards.
- **Configuration**:
- Enabled `revive` in `.golangci.yml`.
- Disabled `golint` to prevent pipeline failures.
- Configured `revive` to ensure it aligns …

Replace deprecated golint with revive

---

operator/es_client.go

> Issue : [#57](https://github.com/zalando-incubator/es-operator/issues/57) (related to some extent)
Adds some debug logs to the draining logic in order to understand a recent issue leading to a stuck scaling operation at draining of a pod.
Increase the visibility of the retrues in order to understand issues with es-operator scale down in light of recent anomalies. During pod draining, es shards are queried to retrieve the shard count per node. There's a retry until the shards are zero on the pod so that the pod can be drained. However it is getting stuck there as per logs. Logs stop printing after a few retries pointing out better logging required at a few places where there's a retry due to errors like json unmarshaling or pod ip exclusion. A debug log would be sufficient which can be …

Add debug logs to monitor retry in waitForEmptyEsNode

---

cmd/e2e/test_utils.go
e2e.sh
operator/autoscaler.go
operator/autoscaler_test.go

Issue: Due to a wrong edge-case handling, when hitting a one-shard-per-node setup, the es-operator will not scale-down further.
Closes https://github.com/zalando-incubator/es-operator/issues/398 
There have been reports of es-operator being stuck during scale-down. It happens in this situation:
- At maximum scaling we have one-shard-per-node
- There is a scaling hint "DOWN" that doesn't execute, as the edge-case of having less than one shard per node (which was meant to avoid over-scaling at scale-up) is triggered.
- Instead of stopping the scaling, ensure that the scaling respects a minimum value of one-shard-per-node.
- Fixes the e2e test which were failing due to duplicate env variable

Bugfix: Allow scale-down when at one-shard-per-node

---

operator/elasticsearch.go
operator/operator.go
operator/operator_test.go

This introduces the use of informers for listing pods and nodes. It's inspired by what is done in external-dns: https://github.com/kubernetes-sigs/external-dns/blob/805555872ee7e27ab15802a86e313120432117fa/source/ingress.go#L78
The main idea of informers are that they use an internal cache which is maintained via a watch. Whenever the operator will do a list pods or list nodes it will read from the internal cache instead of making an API call to the APIServer thus reducing the load which is usually caused by listing pods in big clusters.
This needs a bit of testing before it can be considered. I had to change a lot of `[]v1.Pod` to `[]*v1.Pod` because of the informer semantics, but I don't fully understand the API yet so I won't to make sure we are still using the values in a safe way. …

Use pod and node informers to reduce APIServer load

---

.zappr.yaml

Fixes the "invalid team" warning appearing with every PR.

Fix team assignment in zappr
